import os
import shutil
import socket
import subprocess
import time
import pytest
from mimesis import Internet
from test_helper import ApiTestCase


def built_with_redis_tls():
    # config.h is generated in the build root by configure
    try:
        with open('../config.h') as f:
            return '#define HAVE_LIBHIREDIS_SSL 1' in f.read()
    except OSError:
        return False


def wait_for_port(port, timeout_secs=10):
    for _ in range(timeout_secs * 2):
        try:
            with socket.create_connection(('127.0.0.1', port), timeout=1):
                return True
        except OSError:
            time.sleep(0.5)
    return False


@pytest.mark.skipif(not built_with_redis_tls(),
                    reason="wforce was built without Redis TLS support (hiredis_ssl)")
@pytest.mark.skipif(shutil.which('redis-server') is None,
                    reason="redis-server is not installed")
class TestBlacklistTLS(ApiTestCase):
    # Runs a local TLS-only redis (mutual TLS, using the certs generated by
    # create-certs.sh) and checks that blacklist entries persist across a
    # wforce restart when the redis connection uses TLS.
    redis_proc = None

    @classmethod
    def setUpClass(cls):
        cls.redis_proc = subprocess.Popen(
            ["redis-server", "--port", "0", "--tls-port", "6390",
             "--tls-cert-file", "certs/server.crt",
             "--tls-key-file", "certs/server.key",
             "--tls-ca-cert-file", "certs/root.pem",
             "--save", ""],
            close_fds=True)
        if not wait_for_port(6390):
            cls.redis_proc.terminate()
            cls.redis_proc.wait()
            cls.redis_proc = None
            raise RuntimeError("TLS redis-server did not start on port 6390")

    @classmethod
    def tearDownClass(cls):
        if cls.redis_proc is not None:
            cls.redis_proc.terminate()
            cls.redis_proc.wait()

    def test_PersistBlacklistTLS(self):
        cmd5 = ("../wforce/wforce -D -C ./wforce5.conf -R ../wforce/regexes.yaml").split()
        proc5 = subprocess.Popen(cmd5, close_fds=True)
        self.assertTrue(wait_for_port(self.server5_port),
                        "wforce5 (TLS persist instance) did not start")

        for i in range(100):
            random_ip = Internet().ip_v4()
            r = self.addBLEntryIPPersistTLS(random_ip, 30, "test tls blacklist")
            j = r.json()
            self.assertEqual(j['status'], 'ok')

        proc5.terminate()
        proc5.wait()

        # The entries should be read back from redis over TLS on startup
        proc5 = subprocess.Popen(cmd5, close_fds=True)
        self.assertTrue(wait_for_port(self.server5_port),
                        "wforce5 (TLS persist instance) did not restart")
        time.sleep(1)

        r = self.getBLFuncPersistTLS()
        j = r.json()
        self.assertEqual(len(j['bl_entries']), 100)

        proc5.terminate()
        proc5.wait()
