import os
import shutil
import time
import pytest
from mimesis import Internet
from test_helper import ApiTestCase
from test_helper import running_process
from test_helper import running_process_on_port
from test_helper import start_process
from test_helper import terminate_process
from test_helper import wait_for_port


def built_with_redis_tls():
    # config.h is generated in the build root by configure
    try:
        with open('../config.h') as f:
            return '#define HAVE_LIBHIREDIS_SSL 1' in f.read()
    except OSError:
        return False


@pytest.mark.skipif(not built_with_redis_tls(),
                    reason="wforce was built without Redis TLS support (hiredis_ssl)")
@pytest.mark.skipif(shutil.which('redis-server') is None,
                    reason="redis-server is not installed")
class TestBlacklistTLS(ApiTestCase):
    # Runs a local TLS-only redis (mutual TLS, using the certs generated by
    # create-certs.sh) and checks that blacklist entries persist across a
    # wforce restart when the redis connection uses TLS.
    redis_proc = None

    @classmethod
    def setUpClass(cls):
        proc = start_process(
            ["redis-server", "--port", "0", "--tls-port", "6390",
             "--tls-cert-file", "certs/server.crt",
             "--tls-key-file", "certs/server.key",
             "--tls-ca-cert-file", "certs/root.pem",
             "--save", ""],
            close_fds=True)
        try:
            if not wait_for_port(6390):
                raise RuntimeError("TLS redis-server did not start on port 6390")
        except Exception:
            terminate_process(proc)
            raise
        cls.redis_proc = proc

    @classmethod
    def tearDownClass(cls):
        if cls.redis_proc is not None:
            terminate_process(cls.redis_proc)

    def test_PersistBlacklistTLS(self):
        cmd5 = ("../wforce/wforce -D -C ./wforce5.conf -R ../wforce/regexes.yaml").split()

        with running_process_on_port(cmd5, self.server5_port, close_fds=True):
            for i in range(100):
                random_ip = Internet().ip_v4()
                r = self.addBLEntryIPPersistTLS(random_ip, 30, "test tls blacklist")
                j = r.json()
                self.assertEqual(j['status'], 'ok')

        # The entries should be read back from redis over TLS on startup
        with running_process_on_port(cmd5, self.server5_port, close_fds=True):
            time.sleep(1)

            r = self.getBLFuncPersistTLS()
            j = r.json()
            self.assertEqual(len(j['bl_entries']), 100)

    def test_RedisTLSVerifyPeerDisabled(self):
        cmd_verify = ("../wforce/wforce -D -C ./wforce5-verify-missing-ca.conf -R ../wforce/regexes.yaml").split()
        with running_process(cmd_verify, close_fds=True):
            self.assertFalse(wait_for_port(self.server5_port, 3),
                             "wforce started even though Redis peer verification had no trusted CA")

        cmd_noverify = ("../wforce/wforce -D -C ./wforce5-noverify-missing-ca.conf -R ../wforce/regexes.yaml").split()
        with running_process_on_port(cmd_noverify, self.server5_port, close_fds=True):
            random_ip = Internet().ip_v4()
            r = self.addBLEntryIPPersistTLS(random_ip, 5, "test tls no verify")
            j = r.json()
            self.assertEqual(j['status'], 'ok')
            r = self.delBLEntryIPPersistTLS(random_ip)
            j = r.json()
            self.assertEqual(j['status'], 'ok')
