addListener("0.0.0.0:8088", false, "", "", {})
setWebserverPassword("super")
setKey("MzfImn71m3bYrlPApe+PR7tY/RXoZ4IdpWvUc4o5OnQ=")
controlSocket("0.0.0.0:4108")

blacklistPersistDB("localhost", 6390)
blacklistRedisTLS(true)
blacklistRedisTLSCA("certs/root.pem")
blacklistRedisTLSClientCert("certs/client.crt", "certs/client.key")
blacklistPersistRWTimeout(0, 500000)
whitelistPersistDB("localhost", 6390)
whitelistRedisTLS(true)
whitelistRedisTLSCA("certs/root.pem")
whitelistRedisTLSClientCert("certs/client.crt", "certs/client.key")
whitelistPersistRWTimeout(0, 500000)
