addListener("0.0.0.0:8089", false, "", "", {})
setWebserverPassword("super")
setKey("1bRUa62e0nViOOlUZ4Ez2xA4ho6P4WiwEUwYxWWb6kc=")
controlSocket("0.0.0.0:4109")

addListener("0.0.0.0:8189", true, "certs/server.crt", "certs/server.key", {})
setCurlClientCertAndKey("certs/client.crt", "certs/client.key")
setCurlCABundleFile("certs/root.pem")

dofile("./wforce-tw.conf")

setBlacklistV4Prefix(24)
setBlacklistV6Prefix(64)
setWhitelistV4Prefix(24)
setWhitelistV6Prefix(64)
